#!/usr/bin/env bash
# CANONICAL HOME: Hal0ai/hal0-runner-images runners/promptforge/build.sh (moved
# from Hal0ai/hal0 packaging/runner/promptforge/ @ d2e87915e; docs/CONSOLIDATION.md).
# Default tag is the CONSUMED tag from manifest.toml: for any build meant to
# be pushed, pass `--tag` with a new immutable tag.
# Reproduce the PromptForge runner image from tracked source (#1946).
#
# CANDIDATE recipe: builds ghcr.io/hal0ai/hal0-promptforge:v2.3-qwen38, the
# accelerated-path runner for jcbtc/Qwen3.8-27B-CIRU-ActiveFPX-PromptForge
# (spec 2026-08-29-specialty-distributions). The image this produces is a
# CANDIDATE — DEFAULT_PROMPTFORGE_IMAGE (src/hal0/config/schema.py) does not
# become an unconditional default pin until the gate box A validation gate
# (#1891) passes: the temp-0 Paris probe, the card's stated quality/
# HumanEval envelope, and MTP (depth-4) acceptance. Same discipline #1888
# forced onto DEFAULT_ROCMFPX_IMAGE, applied here before the first build.
#
# Modelled on packaging/runner/rocmfpx/build.sh: everything variable lives
# in manifest.toml; this script only executes it. All pins are resolved as
# of 2026-08-30 (base distro digest, TheRock 7.15 dist tarball url+sha256,
# runtime patch sha256 — see manifest [base] and [[patches]]).
# A clean checkout of this repo plus a build host with docker/podman
# and network is meant to be the entire input, matching rocmfpx's
# reproduction contract — `ade07ba` was a hand-build with no tracked
# recipe, and a signed default pin must never be in that position again.
#
#   ./build.sh                 # build the tag named in the manifest
#   ./build.sh --tag foo:bar   # build under a different tag (candidates)
#   ./build.sh --check         # verify the patch series applies, build nothing
#
# --check needs only git, python3 and network — NO container runtime — so it
# runs on an ordinary CI box. tests/packaging exercises that property for
# rocmfpx; this recipe is not yet wired into CI (task-12 —
# deliverable is the
# tracked recipe, not a runnable build; the build pipeline job and the
# Hal0ai/hal0-runner-images images.json entry that build it are tracked on
# #1946 and are separate follow-up work).
#
# TRADEOFF, stated rather than left for a reader to infer: both Containerfiles
# are generated by heredoc rather than tracked as files. The manifest stays the
# single source of truth that way, but the cost is that reviewers review bash
# interpolation instead of a diffable image definition — and that cost has
# already been paid once, in the symlink-loop escaping bug noted below. If a
# second such bug lands, invert the tradeoff and track the Containerfiles.
#
# NOT run on a production box. Slot inference and image builds compete for the
# same GPU host; build on the dedicated build host.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="${HERE}/manifest.toml"
WORK="${HAL0_RUNNER_BUILD_DIR:-/tmp/hal0-promptforge-build}"
TAG_OVERRIDE=""
CHECK_ONLY=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --tag) TAG_OVERRIDE="$2"; shift 2 ;;
        --check) CHECK_ONLY=1; shift ;;
        *) echo "unknown argument: $1" >&2; exit 64 ;;
    esac
done

# Read the manifest with the stdlib rather than a TOML CLI, so the only build
# dependency is a python3 that already ships on every supported host.
read_manifest() {
    python3 - "$MANIFEST" "$1" <<'PY'
import sys, tomllib
doc = tomllib.load(open(sys.argv[1], "rb"))
cur = doc
for part in sys.argv[2].split("."):
    cur = cur[part]
if isinstance(cur, list):
    print("\n".join(str(x) for x in cur))
else:
    print(cur)
PY
}

TAG="${TAG_OVERRIDE:-$(read_manifest image.tag)}"
BASE="$(read_manifest base.image)"
BASE_DIGEST="$(read_manifest base.digest)"
# Preflight the pins that used to ship blank (the recipe's original open
# TODO): dying here with the manifest's own field names beats dying twenty
# minutes later inside a docker build with a misleading FROM error.
[[ -n "$BASE" && -n "$BASE_DIGEST" ]] || {
    echo "manifest [base] image/digest are blank — resolve the base pins before building (see [base] comments)" >&2
    exit 67
}
# What both FROM lines actually consume. The tag is carried alongside for
# readability only — pulling by digest ignores it, which is the point.
BASE_REF="${BASE}@${BASE_DIGEST}"
# The ROCm toolchain is NOT in the base image (no pullable TheRock container
# exists — see manifest [base]): it is this dist tarball, unpacked into
# /opt/rocm in both stages.
THEROCK_URL="$(read_manifest base.therock.url)"
THEROCK_SHA256="$(read_manifest base.therock.sha256)"
[[ -n "$THEROCK_URL" && -n "$THEROCK_SHA256" ]] || {
    echo "manifest [base.therock] url/sha256 are blank — resolve the TheRock tarball pin before building" >&2
    exit 67
}
REPO="$(read_manifest source.repo)"
REF="$(read_manifest source.ref)"
mapfile -t CMAKE_FLAGS < <(read_manifest build.cmake_flags)
mapfile -t PATCHES < <(python3 - "$MANIFEST" <<'PY'
import sys, tomllib
doc = tomllib.load(open(sys.argv[1], "rb"))
for p in doc.get("patches", []):
    print(p["file"])
PY
)

echo "==> tag    ${TAG}"
echo "==> base   ${BASE}"
echo "==> base@  ${BASE_DIGEST}"
echo "==> source ${REPO} @ ${REF}"
echo "==> patches ${#PATCHES[@]}"

SRC="${WORK}/src"
rm -rf "$SRC"; mkdir -p "$SRC"
# Check out the exact commit, never a branch tip: a branch would silently move
# and the resulting image would stop matching this manifest with no diff to
# show for it.
#
# Clone-then-checkout rather than `fetch --depth 1 <sha>`: fetching an
# arbitrary commit by SHA requires uploadpack.allowReachableSHA1InWant on the
# server, which is off by default and is NOT set on this source. A shallow
# fetch of the branch is no good either — the pinned commit may be older than
# any depth we guess. Correctness beats transfer size for a tool whose entire
# job is reproducing a signed artefact.
git clone -q --no-checkout "$REPO" "$SRC"
git -C "$SRC" checkout -q "$REF"
# Assert rather than echo. `git checkout <full-sha>` cannot silently resolve
# elsewhere and would fail under `set -e` anyway, but this is the one assertion
# the whole file is about, so it should be made rather than implied.
HEAD_SHA="$(git -C "$SRC" rev-parse HEAD)"
[[ "$HEAD_SHA" == "$REF" ]] || {
    echo "checkout landed on ${HEAD_SHA}, manifest pins ${REF}" >&2; exit 66
}
echo "==> checked out ${HEAD_SHA}"

for p in "${PATCHES[@]}"; do
    git -C "$SRC" apply --check "${HERE}/patches/${p}"
    git -C "$SRC" apply "${HERE}/patches/${p}"
    echo "==> applied ${p}"
done

if (( CHECK_ONLY )); then
    echo "==> --check: patch series applies cleanly against ${REF}; nothing built"
    # SCOPE, stated plainly because this is the mode people quote as evidence:
    # --check proves the source ref is reachable and the single runtime patch
    # applies to it. Everything below this line is UNEXERCISED — the TheRock
    # tarball fetch, dnf resolution, the cmake configure against the
    # toolchain, the four build targets, and both container builds. A green
    # --check is not a green build.
    exit 0
fi

# Resolved HERE, deliberately below the --check exit rather than with the other
# manifest reads. --check touches no container runtime, so requiring one made
# the advertised "validates the series, builds nothing" mode unusable on a
# git+python CI runner — which is most of where it is worth running. Worse under
# `set -e`: the assignment takes the substitution's exit status, so on a
# runtime-less host the script died on the RUNTIME line itself, before it could
# reach the readable error on the next one. Keeping this below the exit is what
# lets tests/packaging run --check in CI.
RUNTIME="${HAL0_CONTAINER_RUNTIME:-$(command -v docker || command -v podman || true)}"
[[ -n "$RUNTIME" ]] || { echo "no docker/podman on PATH" >&2; exit 65; }

# Fetch (or reuse) the TheRock dist tarball and verify it against the
# manifest pin BEFORE any container build consumes it. Cached in $WORK so a
# rebuild does not re-pull ~1.8GB; the hash check runs on every build either
# way, so a stale or truncated cache dies here with the manifest value in
# the error, never inside a docker ADD.
THEROCK_TARBALL="${WORK}/$(basename "$THEROCK_URL")"
if [[ ! -f "$THEROCK_TARBALL" ]]; then
    echo "==> fetching TheRock dist tarball"
    curl -fSL -o "${THEROCK_TARBALL}.part" "$THEROCK_URL"
    mv "${THEROCK_TARBALL}.part" "$THEROCK_TARBALL"
fi
ACTUAL_SHA="$(sha256sum "$THEROCK_TARBALL" | cut -d' ' -f1)"
[[ "$ACTUAL_SHA" == "$THEROCK_SHA256" ]] || {
    echo "TheRock tarball sha256 mismatch: got ${ACTUAL_SHA}, manifest pins ${THEROCK_SHA256}" >&2
    exit 68
}
echo "==> TheRock tarball verified (${THEROCK_SHA256})"

# HIP-only image: no vulkan toolchain in the builder (GGML_VULKAN=OFF — the
# defining flag of this recipe), and no rocm dnf packages either: the
# fedora base carries zero ROCm, the toolchain is the ADDed tarball. docker
# ADD auto-extracts a local tar.gz; the dist tarball is root-relative
# (./bin, ./lib, ./share), so it lands as a complete /opt/rocm tree.
BUILDER="localhost/hal0-promptforge-builder:$(read_manifest base.rocm_version)"
ln -f "$THEROCK_TARBALL" "${WORK}/therock-dist.tar.gz" 2>/dev/null \
    || cp "$THEROCK_TARBALL" "${WORK}/therock-dist.tar.gz"
cat > "${WORK}/Containerfile.builder" <<EOF
FROM ${BASE_REF}
RUN dnf install -y \
      gcc gcc-c++ cmake ninja-build make git \
      libcurl-devel \
    && dnf clean all
ADD therock-dist.tar.gz /opt/rocm/
ENV ROCM_PATH=/opt/rocm \\
    PATH=/opt/rocm/bin:/opt/rocm/llvm/bin:\${PATH} \\
    LD_LIBRARY_PATH=/opt/rocm/lib:/opt/rocm/lib/llvm/lib
EOF
"$RUNTIME" build -f "${WORK}/Containerfile.builder" -t "$BUILDER" "$WORK"

# composable_kernel, pinned in [base] — PROMPTFORGE_CK_ROOT in the manifest's
# cmake flags points at ../composable_kernel relative to /src, so it is
# checked out as a sibling and mounted alongside. Same clone-then-checkout
# rationale as the source tree above.
CK_REF="$(read_manifest base.composable_kernel_ref)"
CK="${WORK}/composable_kernel"
if [[ ! -d "$CK/.git" ]]; then
    git clone -q --no-checkout https://github.com/ROCm/composable_kernel.git "$CK"
fi
git -C "$CK" checkout -q "$CK_REF"
CK_HEAD="$(git -C "$CK" rev-parse HEAD)"
[[ "$CK_HEAD" == "$CK_REF" ]] || {
    echo "composable_kernel checkout landed on ${CK_HEAD}, manifest pins ${CK_REF}" >&2; exit 66
}
echo "==> composable_kernel at ${CK_HEAD}"

# `:z` — SELinux shared relabel on the bind mount. Without it the build fails
# on an enforcing host, which is the default on the Fedora/RHEL family this
# whole toolchain targets. Same requirement hal0's own slot mounts document (see
# config/paths.py and the `selinux="z"` Mount flags in providers/). `:z` not
# `:Z` because $SRC is a scratch dir under $WORK that may be reused across
# builds; and unlike the slot mounts there is no NFS caveat here, since $WORK is
# always local scratch on the build host.
#
# Compiler selection follows the card's build section verbatim (TheRock's
# clang out of /opt/rocm/llvm/bin, CMAKE_PREFIX_PATH at the ROCm root)
# rather than rocmfpx's hipconfig indirection — hipconfig ships in the
# tarball but the card's explicit form is what v2.3 was validated with.
"$RUNTIME" run --rm --entrypoint bash \
    -v "${SRC}:/src:z" -v "${CK}:/composable_kernel:z" -w /src \
    -e JOBS="${JOBS:-6}" "$BUILDER" -c "
set -e
export ROCM_PATH=/opt/rocm
cmake -S . -B build \
  -DCMAKE_C_COMPILER=\"\$ROCM_PATH/llvm/bin/clang\" \
  -DCMAKE_CXX_COMPILER=\"\$ROCM_PATH/llvm/bin/clang++\" \
  -DCMAKE_HIP_COMPILER=\"\$ROCM_PATH/llvm/bin/clang++\" \
  -DCMAKE_PREFIX_PATH=\"\$ROCM_PATH\" \
  $(printf '%s ' "${CMAKE_FLAGS[@]}")
cmake --build build -j \"\$JOBS\" --target llama-server llama-cli llama-bench llama-quantize
"

STAGE="${WORK}/stage"
rm -rf "$STAGE"; mkdir -p "$STAGE/bin"
cp -a "${SRC}"/build/bin/. "${STAGE}/bin/"
find "${SRC}/build" -name '*.so*' -exec cp -P {} "${STAGE}/bin/" \;
cp "${HERE}/entrypoint.sh" "${STAGE}/hal0-runner-entrypoint.sh"

# Which REVISION of this recipe built the image. Filenames alone cannot answer
# that: the patch files are mutable in-tree under stable names, so an older
# image labelled `0001-….patch` cannot be traced back to the bytes it was built
# from — which is the whole stated purpose of the label block below. Provenance
# that names a mutable thing is not provenance; same class as pinning the base
# by tag.
RECIPE_REV="$(git -C "$HERE" rev-parse HEAD 2>/dev/null || echo unknown)"
if ! git -C "$HERE" diff --quiet HEAD -- "$HERE" 2>/dev/null; then
    # Say so in the label rather than silently stamping a clean sha onto an
    # image built from edited files.
    RECIPE_REV="${RECIPE_REV}-dirty"
fi
# sha256 over the patch SERIES, in manifest order — immutable even if the files
# are renamed or edited under the same names.
PATCH_SERIES_SHA="$(
    for p in "${PATCHES[@]}"; do cat "${HERE}/patches/${p}"; done | sha256sum | cut -d' ' -f1
)"

ln -f "$THEROCK_TARBALL" "${STAGE}/therock-dist.tar.gz" 2>/dev/null \
    || cp "$THEROCK_TARBALL" "${STAGE}/therock-dist.tar.gz"
cat > "${STAGE}/Containerfile" <<EOF
FROM ${BASE_REF}
# No vulkan packages, deliberately: this is the HIP-only image
# (GGML_VULKAN=OFF is this recipe's defining flag) — pulling mesa/vulkan in
# here was inherited rocmfpx scaffolding, now dropped.
#
# The FULL TheRock dist tree, not a pruned lib/ subset: the runtime needs
# /opt/rocm/lib, /opt/rocm/lib/llvm/lib (card's LD_LIBRARY_PATH), and the
# comgr/device-lib support files whose exact layout varies by TheRock
# nightly — pruning by guesswork risks a runtime-only load failure the
# builder never sees. Cost is image size; prune later with ldd evidence if
# it matters.
ADD therock-dist.tar.gz /opt/rocm/
COPY bin/ /opt/promptforge/bin/
COPY hal0-runner-entrypoint.sh /opt/promptforge/hal0-runner-entrypoint.sh
# UNLIKE rocmfpx there is no stock-toolbox /usr/local/bin/llama-* to scrub
# here — the base is plain fedora-minimal and ships no llama binaries at
# all. NO llama-* is put on PATH either, matching rocmfpx's position (see
# that Containerfile's symlink-loop history): nothing in hal0 today invokes
# THIS image's binaries by an /opt/promptforge/... absolute path —
# src/hal0/bench/harness.py's bench_bin is hardcoded to
# /opt/rocmfpx/bin/llama-bench only (rocmfpx-specific; parameterizing that
# is the ledgered M5 follow-up). LD_LIBRARY_PATH below still covers the
# skipped ldconfig, so the binaries stay reachable under the absolute path.
RUN chmod +x /opt/promptforge/hal0-runner-entrypoint.sh
ENV ROCM_PATH=/opt/rocm \\
    LD_LIBRARY_PATH=/opt/promptforge/bin:/opt/rocm/lib:/opt/rocm/lib/llvm/lib \\
    HSA_OVERRIDE_GFX_VERSION=11.5.1 \\
    GGML_HIP_ENABLE_UNIFIED_MEMORY=1
# Provenance in the image itself, so a box can answer "where did this come
# from" without the repo (#1970). Every value here is immutable: a commit sha,
# a content hash, or a registry digest.
LABEL org.opencontainers.image.source="${REPO}" \\
      org.opencontainers.image.revision="${REF}" \\
      org.opencontainers.image.base.name="${BASE}" \\
      org.opencontainers.image.base.digest="${BASE_DIGEST}" \\
      dev.hal0.runner.recipe="runners/promptforge" \\
      dev.hal0.recipe.revision="${RECIPE_REV}" \\
      dev.hal0.runner.base="${BASE_REF}" \\
      dev.hal0.runner.therock.url="${THEROCK_URL}" \\
      dev.hal0.runner.therock.sha256="${THEROCK_SHA256}" \\
      dev.hal0.runner.patches="$(IFS=,; echo "${PATCHES[*]}")" \\
      dev.hal0.runner.patches.sha256="${PATCH_SERIES_SHA}" \\
      dev.hal0.runner.specialties="promptforge" \\
      dev.hal0.runner.flavor="specialized" \\
      org.opencontainers.image.description="PromptForge/ActiveFPX accelerated runner (HIP-only, GGML_VULKAN=OFF) for jcbtc Qwen3.8 CIRU distributions. NOT the general AMD default — use hal0-combined for ordinary GGUF serving."
ENTRYPOINT ["/opt/promptforge/hal0-runner-entrypoint.sh"]
EOF
"$RUNTIME" build -f "${STAGE}/Containerfile" -t "$TAG" "$STAGE"
echo "==> built ${TAG}"
